language: go

go:
  - 1.6
  - 1.7
  - tip

cache:
  directories:
    - vendor

addons:
  postgresql: "9.5"

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/axw/gocov/gocov
  - go get -u github.com/Masterminds/glide
  - glide up -s -u

before_script:
  - psql -U postgres -c 'CREATE DATABASE go_restful;';

script:
  - glide up -u -s
  - $HOME/gopath/bin/goveralls -service=travis-ci
